### ISSUE TITLE
All steps show as 'undefined steps'

### ISSUE THREAD

**Issue by tk8817** [burtlo/yard-cucumber#70]
Hi folks,

Just upgraded to the latest version and noticed that all of my steps are being classified as 'undefined' in the report. What determines if a step is a 'Step Definition' vs 'Undefined Steps'. 

I have even added this configuration in an attempt to ensure it understands my steps (I am an english speaker).

```yml
:"yard-cucumber":
  language:
    step_definitions: [ 'Given', 'When', 'Then', 'And', 'Soit', 'Etantdonné', 'Lorsque', 'Lorsqu', 'Alors', 'Et' ]
```
